### ISSUE TITLE
Merging changes back to vercel/pkg-fetch

### ISSUE THREAD

**Issue by hipstersmoothie** [jesec/pkg-fetch#3]
Hey! I love all the enhancements you've done here. The automation you've set up is killer! How would you feel merging these changes back into the main fork?

I've been in contact with @leerob who is helping to maintain to maintain the project now and I feel like the community would be better served if these enhancements made it to the main fork.

**Comment by jesec** [comment]
Indeed, CI/automation greatly reduces the costs of maintenance, and users have more confidence in the safety of binaries as the build procedures/logs are public. It also allows us to track minor/patch (some of them security-critical) releases more quickly. However, this project does need a maintainer who are familiar with Node.js core. Patches have to be rebased for each major release of Node.js. So far, I found it difficult to make the rebased patch stable on Node.js 15. 

Good idea. However, I made some changes which might not be appropriate for others' use cases. Changes would have to be reevaluated and cherry-picked into a new branch before a PR to main repo can be created. It will certainly take some time and effort, and I think it would be nice to get some clarifications from upstream first as the upstream is inactive for quite a long time.

**Comment by robertsLando** [comment]
I also have implemented https://github.com/yao-pkg/pkg-binaries/blob/master/build.sh that is used in https://github.com/yao-pkg/pkg-binaries/blob/master/.github/workflows/build.yml to build the node binaries. Using that could be quite easy using matrix to create all the binaries needed

**Comment by jesec** [comment]
I intentionally refrain from using `matrix` of Github Actions. In this project, there are multiple architectures and multiple platforms, each requires (almost completely) different sets of preparations and build steps/arguments. IMO inappropriate abstraction can bring chaoses and confusions. Additionally, it is not portable to non-Unix platforms.

**Comment by robertsLando** [comment]
@jesec could you at least push on pkg-fetch the patch for nodejs 14?
