### ISSUE TITLE
Patch file for v14.16.0 is throwing error

### ISSUE THREAD

**Issue by theaquarian007** [jesec/pkg-fetch#4]
Hi,
I tried to generate a binary for v14.16.0 and used the patch that you have here. I get the following error:

Applying patches
patch: **** Only garbage was found in the patch input.

Not sure what the issue is here?

**Comment by jesec** [comment]
**Learn** how to use `patch` utility first, and make sure that you have the right `patch`. Check CI workflows and related files for details about how to apply a patch: 

https://github.com/jesec/pkg-fetch/blob/aed52efc5cb4a5f6962c1692a094a5816e6801c2/lib/build.js#L61

**Comment by theaquarian007** [comment]
Got it. I think I posted the comment in haste. Apologies! I had been so frustrated as I was not getting anywhere. Seems I grabbed the file incorrectly. It is working fine now.

**Comment by jesec** [comment]
> Got it. I think I posted the comment in haste. Apologies! I had been so frustrated as I was not getting anywhere. Seems I grabbed the file incorrectly. It is working fine now.

Feel free to close the issue.
